### ISSUE TITLE
display of plot heading from measurement

### ISSUE THREAD

**Issue by nexuscomputing** [Photosynq/photosynq-android-v2#19]
display of the top 6 data points needs to be clearer + more defined

**Comment by nexuscomputing** [comment]
changed heading to be multiline for items in "order" array

![device-2016-05-30-155546](https://cloud.githubusercontent.com/assets/5871353/15651317/0e879470-267f-11e6-9ab0-4d671e1e160b.png)

**Comment by gbathree** [comment]
Cool - looks much better, we'll try it out here -

On Mon, May 30, 2016 at 10:13 AM, Nexus Computing <notifications@github.com>
wrote:

> Closed #19 <https://github.com/Photosynq/photosynq-android-v2/issues/19>
> via 67a7124
> <https://github.com/Photosynq/photosynq-android-v2/commit/67a7124a92f8f210b101fcc564dba245e83fa81b>
> .
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Photosynq/photosynq-android-v2/issues/19#event-676091071>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABqWIZwM70vOP7s12zLCcCXB1LxXU0uHks5qGvCigaJpZM4Ip0Uu>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org
